name: loginpge
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.0.0+1




  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  fluttertoast: ^8.0.8
  textfield_search: ^0.10.0
  flutter_native_contact_picker: ^0.0.3
  intl: ^0.17.0
  azlistview: ^2.0.0
  connectivity_plus: ^1.0.6
  firebase_core: ^1.0.4
  firebase_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  fluttertoast: ^8.0.9
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  table_calendar: ^2.1.0
  flutter_easyloading: ^3.0.0
  pdf: ^2.1.0
  universal_html: ^1.2.4



  flutter_lints: ^1.0.0
  sqflite: any
  path_provider: ^2.0.11
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.1
  circles_background: any
  sms_otp_auto_verify: ^2.1.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/back-button.png
    - assets/banner.png
    - assets/button.jpg
    - assets/check.png
    - assets/email.png
    - assets/input-box1.png
    - assets/login-bg.jpg
    - assets/no-check.png
    - assets/password.png
    - assets/top-bar-bg.png
    - assets/setting.png
    - assets/setting-active.png
    - assets/staff.png
    - assets/staff-active.png
    - assets/user.png
    - assets/user-active.png
    - assets/work.png
    - assets/work-active.png
    - assets/otpicon.png
    - assets/filter.png
    - assets/search.png
    - assets/rightarrow.png
    - addicon.png
    - download.png
    - calender.png
    - verified.png
    - uploadicon.png
    - downarrow.png
    - selectIcon.png
    - hamburgermenuicon.png
    - Usericon.png
    - testimonialicon.png




  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
